print(1)
raise ValueError
print(2)

name = "123"
raise NameError("błędna nazwa")
print(name)